name: Environment Workflow

on:
  push:
    branches:
      - main

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dev Environment Webhook
        run: |
          echo "Running in DEV Environment"
          curl -X GET https://jsonplaceholder.typicode.com/todos/1 \
            -H "Content-Type: application/json"
  
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Prod Environment Webhook
        run: |
          echo "Running in Prod Environment"
          curl -X GET https://jsonplaceholder.typicode.com/todos/1 \
            -H "Content-Type: application/json"
  
