name: Environment Workflow

on:
  push:
    branches:
      - main

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run Dev Environment Webhook
        run: |
          echo "Running in DEV Environment"
          curl -X GET -u admin:118268d84df716e1ad80445b97940510a4 http://3.90.185.105:8080/job/devHook/build?token=1234
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: DEV

    steps:
      - name: Run Prod Environment Webhook
        run: |
          echo "Running in Prod Environment"
          curl -X GET -u admin:11c965bd0e7b71e609e764bf2ac5687080 http://34.229.159.186:8080/job/newitem/build?token=1234
  
