name: Environment Workflow

on:
  push:
    branches:
      - main

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run Dev Environment Webhook
        run: |
          echo "Running in DEV Environment"
          curl -X GET admin:118268d84df716e1ad80445b97940510a4 http://3.90.185.105:8080/job/devHook/build?token=1234
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: DEV

    steps:
      - name: Run Prod Environment Webhook
        run: |
          echo "Running in Prod Environment"
          curl -X GET https://jsonplaceholder.typicode.com/todos/1 \
            -H "Content-Type: application/json"
  
